import type { BlockData, BlockType, PageTheme } from "@/lib/db/schema";
import { getPresetById, themePresets } from "@/lib/themes";

export type TemplateBlock = {
  type: BlockType;
  data: BlockData;
};

export type PageTemplate = {
  id: string;
  name: string;
  category: string;
  emoji: string;
  description: string;
  themePresetId: string;
  suggestedTitle: string;
  suggestedBio: string;
  blocks: TemplateBlock[];
  featured?: boolean; // mostra na seção Populares quando não há dados reais
};

// ============== HELPERS ==============

const link = (label: string, url: string): TemplateBlock => ({
  type: "link",
  data: { kind: "link", label, url },
});
const text = (content: string): TemplateBlock => ({
  type: "text",
  data: { kind: "text", content, align: "center" },
});
const divider: TemplateBlock = { type: "divider", data: { kind: "divider" } };

// ============== 50 TEMPLATES ==============

export const pageTemplates: PageTemplate[] = [
  // =============== CRIADOR ===============
  {
    id: "creator",
    name: "Criador de conteúdo",
    category: "Criador",
    emoji: "✨",
    description: "Pra quem vive de Instagram, TikTok e YouTube.",
    themePresetId: "midnight",
    suggestedTitle: "Seu @",
    suggestedBio: "Criador de conteúdo · Apaixonado por [seu nicho]",
    featured: true,
    blocks: [
      link("📸 Instagram", "https://instagram.com/"),
      link("🎵 TikTok", "https://tiktok.com/@"),
      link("▶️ YouTube", "https://youtube.com/@"),
      link("🎙 Spotify", "https://open.spotify.com/"),
      divider,
      link("💼 Parcerias", "mailto:contato@email.com"),
    ],
  },
  {
    id: "streamer",
    name: "Streamer",
    category: "Criador",
    emoji: "🎮",
    description: "Twitch, YouTube Live, horários de stream.",
    themePresetId: "cyber",
    suggestedTitle: "@SeuNick",
    suggestedBio: "STREAMER · LIVE 20H TODA NOITE",
    featured: true,
    blocks: [
      text("🔴 AO VIVO · qua, qui, sex 20h"),
      link("🎮 TWITCH", "https://twitch.tv/"),
      link("▶️ YOUTUBE", "https://youtube.com/@"),
      link("💬 DISCORD", "https://discord.gg/"),
      divider,
      link("💎 APOIAR", "https://patreon.com/"),
      link("𝕏 TWITTER", "https://x.com/"),
    ],
  },
  {
    id: "lifestyle",
    name: "Influencer lifestyle",
    category: "Criador",
    emoji: "🌸",
    description: "Moda, casa, rotina, viagens.",
    themePresetId: "pastel-paper",
    suggestedTitle: "Seu nome",
    suggestedBio: "Lifestyle · Moda · Viagem 📍 [cidade]",
    blocks: [
      link("📸 Instagram", "https://instagram.com/"),
      link("🎀 Pinterest", "https://pinterest.com/"),
      link("🎵 TikTok", "https://tiktok.com/@"),
      divider,
      link("🛍 Meus favoritos", "https://"),
      link("💌 Contato", "mailto:"),
    ],
  },
  {
    id: "gamer",
    name: "Creator gamer",
    category: "Criador",
    emoji: "👾",
    description: "Gameplays, reviews e highlights.",
    themePresetId: "midnight-glow",
    suggestedTitle: "@SeuGamer",
    suggestedBio: "Gamer · FPS · Battle Royale",
    blocks: [
      link("▶️ Canal principal", "https://youtube.com/@"),
      link("🎵 Shorts no TikTok", "https://tiktok.com/@"),
      link("🎮 Twitch", "https://twitch.tv/"),
      link("💬 Discord da galera", "https://discord.gg/"),
      divider,
      link("𝕏 Twitter", "https://x.com/"),
    ],
  },
  {
    id: "reviewer",
    name: "Reviewer / Crítico",
    category: "Criador",
    emoji: "⭐",
    description: "Filmes, livros, tecnologia.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Reviews sem firulas · [seu nicho]",
    blocks: [
      link("Canal no YouTube", "https://youtube.com/@"),
      link("Letterboxd", "https://letterboxd.com/"),
      link("Instagram", "https://instagram.com/"),
      divider,
      link("Contato pra mídia", "mailto:"),
    ],
  },
  {
    id: "micro-influencer",
    name: "Micro-influencer",
    category: "Criador",
    emoji: "💫",
    description: "Pra quem está começando — foco em conversão.",
    themePresetId: "candy",
    suggestedTitle: "@seuuser",
    suggestedBio: "Dicas diárias · [seu tema]",
    blocks: [
      link("📸 Me segue no Insta", "https://instagram.com/"),
      link("🎵 TikTok", "https://tiktok.com/@"),
      link("📺 Meu canal", "https://youtube.com/@"),
      divider,
      link("💼 Parcerias", "mailto:"),
    ],
  },
  // =============== MÚSICA ===============
  {
    id: "musician",
    name: "Músico / Banda",
    category: "Música",
    emoji: "🎸",
    description: "Lance seu single, venda ingresso.",
    themePresetId: "electric",
    suggestedTitle: "Nome do artista",
    suggestedBio: "Novo single fora agora 🔥",
    featured: true,
    blocks: [
      text("Ouça em todas as plataformas"),
      link("🎧 Spotify", "https://open.spotify.com/"),
      link("🍎 Apple Music", "https://music.apple.com/"),
      link("▶️ YouTube Music", "https://music.youtube.com/"),
      divider,
      link("🎫 Comprar ingresso", "https://"),
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "dj",
    name: "DJ",
    category: "Música",
    emoji: "🎧",
    description: "Sets, shows e streams.",
    themePresetId: "cyber",
    suggestedTitle: "DJ NAME",
    suggestedBio: "HOUSE / TECHNO / BRAZIL",
    blocks: [
      link("SOUNDCLOUD", "https://soundcloud.com/"),
      link("SPOTIFY", "https://open.spotify.com/"),
      link("YOUTUBE", "https://youtube.com/@"),
      divider,
      link("PRÓXIMOS SHOWS", "https://"),
      link("INSTAGRAM", "https://instagram.com/"),
    ],
  },
  {
    id: "producer",
    name: "Produtor musical",
    category: "Música",
    emoji: "🎚",
    description: "Portfolio de beats e parcerias.",
    themePresetId: "midnight-glow",
    suggestedTitle: "Producer Name",
    suggestedBio: "Beats · Mix · Master",
    blocks: [
      link("🎵 Ouça os beats", "https://soundcloud.com/"),
      link("💎 Comprar beat", "https://beatstars.com/"),
      link("▶️ YouTube", "https://youtube.com/@"),
      divider,
      link("📧 Contato pra artistas", "mailto:"),
    ],
  },
  {
    id: "rapper",
    name: "Rapper / Hip-hop",
    category: "Música",
    emoji: "🎤",
    description: "Estilo cru, direto ao ponto.",
    themePresetId: "noir",
    suggestedTitle: "MC NAME",
    suggestedBio: "RAP · TRAP · SP",
    blocks: [
      link("🎧 SPOTIFY", "https://open.spotify.com/"),
      link("▶️ CLIPES", "https://youtube.com/@"),
      link("🎵 TIKTOK", "https://tiktok.com/@"),
      divider,
      link("🔥 NOVO SINGLE", "https://"),
      link("📸 @", "https://instagram.com/"),
    ],
  },
  {
    id: "orchestra",
    name: "Coral / Orquestra",
    category: "Música",
    emoji: "🎼",
    description: "Música clássica, eventos, apresentações.",
    themePresetId: "sand",
    suggestedTitle: "Nome do grupo",
    suggestedBio: "Música erudita · Fundado em [ano]",
    blocks: [
      link("Agenda de concertos", "https://"),
      link("Canal no YouTube", "https://youtube.com/@"),
      link("Spotify", "https://open.spotify.com/"),
      divider,
      link("Contratar apresentação", "mailto:"),
    ],
  },
  // =============== NEGÓCIO LOCAL ===============
  {
    id: "restaurant",
    name: "Restaurante / Cafeteria",
    category: "Negócio local",
    emoji: "☕",
    description: "Cardápio, delivery, localização.",
    themePresetId: "terracotta",
    suggestedTitle: "Nome do lugar",
    suggestedBio: "Café de especialidade · [sua cidade]",
    featured: true,
    blocks: [
      link("📋 Ver cardápio", "https://"),
      link("🛵 Pedir no iFood", "https://www.ifood.com.br/"),
      link("📱 WhatsApp", "https://wa.me/55"),
      divider,
      link("📍 Como chegar", "https://maps.google.com/"),
      text("Seg a Sex · 8h–18h · Sáb · 9h–16h"),
      link("📸 @nossorestaurante", "https://instagram.com/"),
    ],
  },
  {
    id: "barber",
    name: "Barbearia",
    category: "Negócio local",
    emoji: "💈",
    description: "Agendamento, preços, endereço.",
    themePresetId: "noir",
    suggestedTitle: "NOME DA BARBEARIA",
    suggestedBio: "ESTILO E PRECISÃO · [sua cidade]",
    blocks: [
      link("✂️ AGENDAR HORÁRIO", "https://"),
      link("💬 WHATSAPP", "https://wa.me/55"),
      link("📋 TABELA DE PREÇOS", "https://"),
      divider,
      link("📍 LOCALIZAÇÃO", "https://maps.google.com/"),
      link("📸 INSTAGRAM", "https://instagram.com/"),
    ],
  },
  {
    id: "salon",
    name: "Salão de beleza",
    category: "Negócio local",
    emoji: "💅",
    description: "Agendamento online, portfólio.",
    themePresetId: "blush",
    suggestedTitle: "Nome do salão",
    suggestedBio: "Cabelo · Unhas · Beleza",
    blocks: [
      link("💅 Agendar horário", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("✨ Serviços e preços", "https://"),
      divider,
      link("📸 Portfólio", "https://instagram.com/"),
      link("📍 Endereço", "https://maps.google.com/"),
    ],
  },
  {
    id: "clothing-store",
    name: "Loja de roupas (física)",
    category: "Negócio local",
    emoji: "👗",
    description: "Visite a loja, WhatsApp.",
    themePresetId: "peach-cream",
    suggestedTitle: "Nome da loja",
    suggestedBio: "Moda feita com amor · [cidade]",
    blocks: [
      link("🛍 Novidades da semana", "https://"),
      link("💬 WhatsApp pra comprar", "https://wa.me/55"),
      link("📸 Instagram", "https://instagram.com/"),
      divider,
      link("📍 Venha visitar", "https://maps.google.com/"),
    ],
  },
  {
    id: "tattoo",
    name: "Estúdio de tatuagem",
    category: "Negócio local",
    emoji: "🎨",
    description: "Portfolio, agendamento, estilos.",
    themePresetId: "noir",
    suggestedTitle: "NOME DO ARTISTA",
    suggestedBio: "TATTOO · BLACKWORK · [CIDADE]",
    blocks: [
      link("📸 PORTFÓLIO", "https://instagram.com/"),
      link("📅 AGENDAR", "https://"),
      link("💬 WHATSAPP", "https://wa.me/55"),
      divider,
      link("📍 ESTÚDIO", "https://maps.google.com/"),
    ],
  },
  {
    id: "gym",
    name: "Academia",
    category: "Negócio local",
    emoji: "🏋️",
    description: "Matrícula, aulas, horários.",
    themePresetId: "electric",
    suggestedTitle: "Nome da academia",
    suggestedBio: "Treino forte · Resultados reais",
    blocks: [
      link("💪 Matricular agora", "https://"),
      link("📅 Aula experimental grátis", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      divider,
      link("🏃 Aulas e horários", "https://"),
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "petshop",
    name: "Pet shop",
    category: "Negócio local",
    emoji: "🐾",
    description: "Banho, tosa, produtos.",
    themePresetId: "candy",
    suggestedTitle: "Nome do pet shop",
    suggestedBio: "Seu pet merece · [sua cidade]",
    blocks: [
      link("🐶 Agendar banho e tosa", "https://"),
      link("🛒 Comprar no WhatsApp", "https://wa.me/55"),
      link("🚚 Delivery de ração", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("📍 Endereço", "https://maps.google.com/"),
    ],
  },
  {
    id: "florist",
    name: "Floricultura",
    category: "Negócio local",
    emoji: "🌸",
    description: "Buquês, entregas, eventos.",
    themePresetId: "blush",
    suggestedTitle: "Nome da floricultura",
    suggestedBio: "Flores frescas · Entrega no mesmo dia",
    blocks: [
      link("💐 Ver buquês", "https://"),
      link("💬 Encomendar no WhatsApp", "https://wa.me/55"),
      link("💍 Para casamentos", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  // =============== COMÉRCIO ONLINE ===============
  {
    id: "shop",
    name: "Loja online",
    category: "Comércio",
    emoji: "🛍",
    description: "Venda e direcione pro WhatsApp.",
    themePresetId: "candy",
    suggestedTitle: "Sua loja",
    suggestedBio: "Moda feita com amor · Frete pra todo Brasil",
    blocks: [
      link("🛒 Comprar agora", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("⭐ Novidades da semana", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("🎵 TikTok", "https://tiktok.com/@"),
    ],
  },
  {
    id: "fashion-ecommerce",
    name: "Moda online",
    category: "Comércio",
    emoji: "👚",
    description: "Lookbook, drops, collab.",
    themePresetId: "blush",
    suggestedTitle: "Nome da marca",
    suggestedBio: "Nova coleção disponível",
    blocks: [
      link("🆕 Nova coleção", "https://"),
      link("🔥 Mais vendidos", "https://"),
      link("💌 Cadastrar-se no newsletter", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("💬 Atendimento", "https://wa.me/55"),
    ],
  },
  {
    id: "sweet-shop",
    name: "Doceria / Confeitaria",
    category: "Comércio",
    emoji: "🧁",
    description: "Bolos, brigadeiros, encomendas.",
    themePresetId: "peach-cream",
    suggestedTitle: "Nome da doceria",
    suggestedBio: "Doces artesanais · Encomendas abertas",
    blocks: [
      link("🎂 Encomendar bolo", "https://wa.me/55"),
      link("🍫 Ver cardápio", "https://"),
      link("💝 Festas e eventos", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "handmade",
    name: "Artesanato / Handmade",
    category: "Comércio",
    emoji: "🧶",
    description: "Peças únicas feitas à mão.",
    themePresetId: "terracotta",
    suggestedTitle: "Nome da marca",
    suggestedBio: "Peças únicas feitas à mão",
    blocks: [
      link("🛒 Elo7", "https://elo7.com.br/"),
      link("🛍 Shopee", "https://shopee.com.br/"),
      link("📦 Mercado Livre", "https://mercadolivre.com.br/"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "jewelry",
    name: "Joias & Acessórios",
    category: "Comércio",
    emoji: "💎",
    description: "Peças delicadas, unissex, semijoias.",
    themePresetId: "rose",
    suggestedTitle: "Nome da marca",
    suggestedBio: "Joias que marcam · Folheados a ouro 18k",
    blocks: [
      link("💎 Ver coleção", "https://"),
      link("💬 Atendimento WhatsApp", "https://wa.me/55"),
      link("🎁 Para presente", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  // =============== MÍDIA ===============
  {
    id: "podcaster",
    name: "Podcaster",
    category: "Mídia",
    emoji: "🎙",
    description: "Todos os episódios, em todo canto.",
    themePresetId: "ocean",
    suggestedTitle: "Nome do podcast",
    suggestedBio: "Conversas sobre [tema]",
    featured: true,
    blocks: [
      text("Novo episódio toda quarta 🎧"),
      link("🎧 Spotify", "https://open.spotify.com/show/"),
      link("🍎 Apple Podcasts", "https://podcasts.apple.com/"),
      link("▶️ YouTube", "https://youtube.com/@"),
      divider,
      link("💜 Apoie no Patreon", "https://patreon.com/"),
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "author",
    name: "Autor / Escritor",
    category: "Mídia",
    emoji: "📚",
    description: "Livros, newsletter, resenhas.",
    themePresetId: "rose",
    suggestedTitle: "Nome do autor",
    suggestedBio: "Escritor · [Seu gênero]",
    blocks: [
      link("📖 Meu último livro", "https://"),
      link("⭐ Goodreads", "https://goodreads.com/"),
      link("📨 Newsletter", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "journalist",
    name: "Jornalista / Blogger",
    category: "Mídia",
    emoji: "📰",
    description: "Últimas matérias, contato, portfolio.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Jornalista · Cobertura em [área]",
    blocks: [
      link("Últimas matérias", "https://"),
      link("Portfolio", "https://"),
      link("LinkedIn", "https://linkedin.com/in/"),
      divider,
      link("Contato pra mídia", "mailto:"),
    ],
  },
  {
    id: "newsletter",
    name: "Newsletter",
    category: "Mídia",
    emoji: "📨",
    description: "Assinantes, arquivo, inscrição.",
    themePresetId: "sand",
    suggestedTitle: "Nome da newsletter",
    suggestedBio: "Toda semana na sua caixa · [tema]",
    blocks: [
      link("📬 Assinar grátis", "https://"),
      link("📚 Ler arquivo", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("𝕏 Twitter", "https://x.com/"),
    ],
  },
  {
    id: "blog",
    name: "Blog pessoal",
    category: "Mídia",
    emoji: "✍️",
    description: "Posts, canais sociais, feed.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Escrevo sobre [tema]",
    blocks: [
      link("Últimos posts", "https://"),
      link("Sobre mim", "https://"),
      divider,
      link("Instagram", "https://instagram.com/"),
      link("RSS", "https://"),
    ],
  },
  // =============== PORTFÓLIO ===============
  {
    id: "photographer",
    name: "Fotógrafo",
    category: "Portfólio",
    emoji: "📷",
    description: "Portfolio limpo.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Fotografia de casamento · São Paulo",
    blocks: [
      link("Portfólio", "https://"),
      link("Instagram", "https://instagram.com/"),
      link("Behance", "https://behance.net/"),
      divider,
      link("Orçamento", "mailto:"),
    ],
  },
  {
    id: "portfolio",
    name: "Freelancer / Dev",
    category: "Portfólio",
    emoji: "💻",
    description: "Código, projetos, LinkedIn.",
    themePresetId: "brutalism",
    suggestedTitle: "Seu nome",
    suggestedBio: "Full-stack developer · 8 anos de estrada",
    blocks: [
      link("→ Ver projetos", "https://"),
      link("→ GitHub", "https://github.com/"),
      link("→ LinkedIn", "https://linkedin.com/in/"),
      divider,
      link("→ Contratar", "mailto:"),
    ],
  },
  {
    id: "designer",
    name: "Designer",
    category: "Portfólio",
    emoji: "🎨",
    description: "Dribbble, Behance, case studies.",
    themePresetId: "mist",
    suggestedTitle: "Seu nome",
    suggestedBio: "Product designer · Branding",
    blocks: [
      link("🎨 Dribbble", "https://dribbble.com/"),
      link("📐 Behance", "https://behance.net/"),
      link("💼 LinkedIn", "https://linkedin.com/in/"),
      divider,
      link("💌 Contratar", "mailto:"),
    ],
  },
  {
    id: "architect",
    name: "Arquiteto",
    category: "Portfólio",
    emoji: "🏛",
    description: "Projetos, residencial, comercial.",
    themePresetId: "sand",
    suggestedTitle: "Nome do arquiteto",
    suggestedBio: "Arquitetura & interiores",
    blocks: [
      link("Portfolio de projetos", "https://"),
      link("Instagram", "https://instagram.com/"),
      link("Pinterest", "https://pinterest.com/"),
      divider,
      link("Orçamento", "mailto:"),
    ],
  },
  {
    id: "lawyer",
    name: "Advogado",
    category: "Portfólio",
    emoji: "⚖️",
    description: "Áreas de atuação, contato.",
    themePresetId: "bordeaux",
    suggestedTitle: "Dr. Seu Nome",
    suggestedBio: "Direito empresarial · OAB/[UF] [número]",
    blocks: [
      link("Áreas de atuação", "https://"),
      link("LinkedIn", "https://linkedin.com/in/"),
      link("📞 Agendar consulta", "https://wa.me/55"),
      divider,
      link("📧 Email", "mailto:"),
    ],
  },
  {
    id: "videographer",
    name: "Videomaker",
    category: "Portfólio",
    emoji: "🎬",
    description: "Reels, Vimeo, portfolio.",
    themePresetId: "noir",
    suggestedTitle: "Seu nome",
    suggestedBio: "Videomaker · Brand films · Music videos",
    blocks: [
      link("🎬 Vimeo", "https://vimeo.com/"),
      link("▶️ YouTube", "https://youtube.com/@"),
      link("📸 Instagram", "https://instagram.com/"),
      divider,
      link("💼 Orçamento", "mailto:"),
    ],
  },
  // =============== FITNESS/BEM-ESTAR ===============
  {
    id: "trainer",
    name: "Personal Trainer",
    category: "Fitness",
    emoji: "💪",
    description: "Online + presencial.",
    themePresetId: "electric",
    suggestedTitle: "Coach @",
    suggestedBio: "Seu próximo nível · Online + presencial SP",
    blocks: [
      link("🔥 Começar meu programa", "https://"),
      link("📅 Agendar avaliação", "https://calendly.com/"),
      link("💬 WhatsApp", "https://wa.me/55"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("🎵 TikTok", "https://tiktok.com/@"),
    ],
  },
  {
    id: "nutritionist",
    name: "Nutricionista",
    category: "Fitness",
    emoji: "🥗",
    description: "Consultas, receitas, depoimentos.",
    themePresetId: "pine",
    suggestedTitle: "Dr(a). Seu nome",
    suggestedBio: "Nutricionista clínica · CRN-[número]",
    blocks: [
      link("📅 Agendar consulta", "https://"),
      link("🥑 Receitas gratuitas", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "yoga",
    name: "Yoga / Pilates",
    category: "Fitness",
    emoji: "🧘",
    description: "Aulas online, retiros, agenda.",
    themePresetId: "sand",
    suggestedTitle: "Seu nome",
    suggestedBio: "Instrutor(a) de yoga · Vinyasa · Yin",
    blocks: [
      link("🧘 Aulas online", "https://"),
      link("📅 Agenda semanal", "https://"),
      link("🏝 Próximo retiro", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "dentist",
    name: "Dentista",
    category: "Fitness",
    emoji: "🦷",
    description: "Agendamento, especialidades.",
    themePresetId: "minimal-white",
    suggestedTitle: "Dr(a). Seu nome",
    suggestedBio: "Odontologia estética · CRO-[UF] [número]",
    blocks: [
      link("📅 Agendar consulta", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("🦷 Tratamentos", "https://"),
      divider,
      link("📍 Endereço", "https://maps.google.com/"),
    ],
  },
  {
    id: "therapist",
    name: "Terapeuta / Psicólogo",
    category: "Fitness",
    emoji: "🧠",
    description: "Sessões online, abordagem.",
    themePresetId: "pastel-paper",
    suggestedTitle: "Dr(a). Seu nome",
    suggestedBio: "Psicóloga · CRP-[número]",
    blocks: [
      link("📅 Agendar sessão", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("📝 Sobre minha abordagem", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  // =============== EDUCAÇÃO ===============
  {
    id: "teacher",
    name: "Professor particular",
    category: "Educação",
    emoji: "📚",
    description: "Aulas, horários, contato.",
    themePresetId: "sand",
    suggestedTitle: "Prof. Seu nome",
    suggestedBio: "Matemática e Física · ENEM + Vestibular",
    blocks: [
      link("📅 Agendar aula", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("📝 Material gratuito", "https://"),
      divider,
      link("▶️ YouTube", "https://youtube.com/@"),
    ],
  },
  {
    id: "course",
    name: "Curso online",
    category: "Educação",
    emoji: "🎓",
    description: "Landing do curso, depoimentos.",
    themePresetId: "dusk",
    suggestedTitle: "Nome do curso",
    suggestedBio: "Aprenda [assunto] do zero ao pro",
    featured: true,
    blocks: [
      link("🎓 Matricular-se agora", "https://"),
      link("📺 Aula gratuita", "https://"),
      link("⭐ Depoimentos", "https://"),
      divider,
      link("💬 Dúvidas? Falar no WhatsApp", "https://wa.me/55"),
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "tutor",
    name: "Tutor / Mentor",
    category: "Educação",
    emoji: "🎯",
    description: "Mentoria 1:1, sobre, depoimentos.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Mentor · [área] · 10+ anos",
    blocks: [
      link("🎯 Agendar mentoria", "https://calendly.com/"),
      link("📝 Meu método", "https://"),
      link("⭐ Depoimentos", "https://"),
      divider,
      link("💼 LinkedIn", "https://linkedin.com/in/"),
    ],
  },
  {
    id: "language-school",
    name: "Escola de idiomas",
    category: "Educação",
    emoji: "🌎",
    description: "Cursos, aula experimental.",
    themePresetId: "ocean",
    suggestedTitle: "Nome da escola",
    suggestedBio: "Aulas de inglês · Online + presencial",
    blocks: [
      link("🎁 Aula experimental grátis", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      link("📋 Ver turmas", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  // =============== BELEZA & MODA ===============
  {
    id: "makeup-artist",
    name: "Maquiadora",
    category: "Beleza",
    emoji: "💄",
    description: "Portfólio, casamentos, agenda.",
    themePresetId: "rose",
    suggestedTitle: "Seu nome",
    suggestedBio: "Maquiagem social · Noivas · Eventos",
    blocks: [
      link("💄 Portfolio", "https://instagram.com/"),
      link("💍 Para noivas", "https://"),
      link("📅 Agendar", "https://"),
      divider,
      link("💬 WhatsApp", "https://wa.me/55"),
    ],
  },
  {
    id: "hairdresser",
    name: "Cabeleireira",
    category: "Beleza",
    emoji: "💇",
    description: "Cortes, coloração, tratamentos.",
    themePresetId: "blush",
    suggestedTitle: "Seu nome",
    suggestedBio: "Cabelos · Cortes · Coloração",
    blocks: [
      link("💇 Agendar horário", "https://"),
      link("✨ Meus serviços", "https://"),
      link("💬 WhatsApp", "https://wa.me/55"),
      divider,
      link("📸 Antes e depois", "https://instagram.com/"),
    ],
  },
  {
    id: "model",
    name: "Modelo",
    category: "Beleza",
    emoji: "👠",
    description: "Book, agenciamento, campanhas.",
    themePresetId: "noir",
    suggestedTitle: "SEU NOME",
    suggestedBio: "MODEL · [AGÊNCIA]",
    blocks: [
      link("📸 BOOK", "https://instagram.com/"),
      link("🎬 REEL", "https://"),
      link("📧 MANAGEMENT", "mailto:"),
      divider,
      link("𝕏 TWITTER", "https://x.com/"),
    ],
  },
  // =============== OUTROS ===============
  {
    id: "consultant",
    name: "Consultor / Coach",
    category: "Outros",
    emoji: "💼",
    description: "Consultoria, método, sessão grátis.",
    themePresetId: "mist",
    suggestedTitle: "Seu nome",
    suggestedBio: "Consultor(a) · [área]",
    blocks: [
      link("🎁 Sessão diagnóstico grátis", "https://calendly.com/"),
      link("📝 Meu método", "https://"),
      link("⭐ Cases e depoimentos", "https://"),
      divider,
      link("💼 LinkedIn", "https://linkedin.com/in/"),
      link("📧 Contato", "mailto:"),
    ],
  },
  {
    id: "realestate",
    name: "Imobiliária / Corretor",
    category: "Outros",
    emoji: "🏠",
    description: "Imóveis, WhatsApp, cidade.",
    themePresetId: "minimal-white",
    suggestedTitle: "Seu nome",
    suggestedBio: "Corretor de imóveis · CRECI-[UF] [número]",
    blocks: [
      link("🏠 Imóveis disponíveis", "https://"),
      link("💬 WhatsApp pra visita", "https://wa.me/55"),
      link("📍 Bairros que atendo", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
    ],
  },
  {
    id: "nonprofit",
    name: "ONG / Causa social",
    category: "Outros",
    emoji: "💚",
    description: "Doar, voluntariar, causas.",
    themePresetId: "pine",
    suggestedTitle: "Nome da ONG",
    suggestedBio: "Transformando vidas desde [ano]",
    blocks: [
      link("💚 Doar agora", "https://"),
      link("🤝 Ser voluntário", "https://"),
      link("📰 Nossos projetos", "https://"),
      divider,
      link("📸 Instagram", "https://instagram.com/"),
      link("📧 Contato", "mailto:"),
    ],
  },
  // =============== EM BRANCO ===============
  {
    id: "blank",
    name: "Em branco",
    category: "Do zero",
    emoji: "✍️",
    description: "Começa do zero, sem nada pré-preenchido.",
    themePresetId: "minimal-white",
    suggestedTitle: "Meu link",
    suggestedBio: "",
    blocks: [],
  },
];

export function getTemplateById(id: string): PageTemplate | undefined {
  return pageTemplates.find((t) => t.id === id);
}

export function getTemplateTheme(template: PageTemplate): PageTheme {
  const preset =
    getPresetById(template.themePresetId) ??
    themePresets.find((p) => p.id === "minimal-white")!;
  return preset.theme;
}

export function getTemplateCategories(): string[] {
  const set = new Set<string>();
  pageTemplates.forEach((t) => set.add(t.category));
  return Array.from(set);
}
