import type { PageTheme } from "@/lib/db/schema";

export type ThemePreset = {
  id: string;
  name: string;
  vibe: string;
  theme: PageTheme;
};

export const themePresets: ThemePreset[] = [
  {
    id: "midnight",
    name: "Midnight",
    vibe: "noturno · místico",
    theme: {
      preset: "midnight",
      background: {
        type: "gradient",
        from: "#0f0b29",
        via: "#1e1b4b",
        to: "#312e81",
        direction: "to-br",
      },
      foreground: "#f5f3ff",
      mutedForeground: "#c4b5fd",
      accent: "#a78bfa",
      accentForeground: "#0f0b29",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "glass",
      avatarShape: "circle",
      spacing: "normal",
      effect: "stars",
    },
  },
  {
    id: "sunset",
    name: "Sunset",
    vibe: "quente · vibrante",
    theme: {
      preset: "sunset",
      background: {
        type: "gradient",
        from: "#fb923c",
        via: "#ec4899",
        to: "#8b5cf6",
        direction: "to-br",
      },
      foreground: "#ffffff",
      mutedForeground: "#fef3c7",
      accent: "#ffffff",
      accentForeground: "#ec4899",
      font: "poppins",
      titleFont: "poppins",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "y2k",
    name: "Y2K",
    vibe: "chrome · retro",
    theme: {
      preset: "y2k",
      background: {
        type: "gradient",
        from: "#c0c0c0",
        via: "#e5e7eb",
        to: "#d1d5db",
        direction: "to-b",
      },
      foreground: "#1f2937",
      mutedForeground: "#4b5563",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      font: "bebas",
      titleFont: "bebas",
      buttonStyle: "sharp",
      avatarShape: "square",
      spacing: "tight",
      effect: "grid",
    },
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    vibe: "limpo · editorial",
    theme: {
      preset: "minimal-white",
      background: { type: "solid", color: "#ffffff" },
      foreground: "#0a0a0a",
      mutedForeground: "#737373",
      accent: "#0a0a0a",
      accentForeground: "#ffffff",
      font: "inter",
      titleFont: "instrument-serif",
      buttonStyle: "underline",
      avatarShape: "circle",
      spacing: "loose",
      effect: "none",
    },
  },
  {
    id: "cyber",
    name: "Cyber",
    vibe: "neon · futurista",
    theme: {
      preset: "cyber",
      background: { type: "solid", color: "#050505" },
      foreground: "#d4ff00",
      mutedForeground: "#84cc16",
      accent: "#d4ff00",
      accentForeground: "#050505",
      font: "jetbrains-mono",
      titleFont: "jetbrains-mono",
      buttonStyle: "outline",
      avatarShape: "square",
      spacing: "tight",
      effect: "grid",
    },
  },
  {
    id: "candy",
    name: "Candy",
    vibe: "doce · fofo",
    theme: {
      preset: "candy",
      background: {
        type: "gradient",
        from: "#fce7f3",
        via: "#ddd6fe",
        to: "#bfdbfe",
        direction: "to-br",
      },
      foreground: "#1e1b4b",
      mutedForeground: "#6b21a8",
      accent: "#ec4899",
      accentForeground: "#ffffff",
      font: "dm-sans",
      titleFont: "dm-sans",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "brutalism",
    name: "Brutalism",
    vibe: "raw · ousado",
    theme: {
      preset: "brutalism",
      background: { type: "solid", color: "#fef3c7" },
      foreground: "#0a0a0a",
      mutedForeground: "#292524",
      accent: "#0a0a0a",
      accentForeground: "#fef3c7",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "neubrutalism",
      avatarShape: "square",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "terracotta",
    name: "Terracotta",
    vibe: "terroso · artesanal",
    theme: {
      preset: "terracotta",
      background: { type: "solid", color: "#fef2e0" },
      foreground: "#431407",
      mutedForeground: "#9a3412",
      accent: "#c2410c",
      accentForeground: "#fef2e0",
      font: "playfair",
      titleFont: "playfair",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "loose",
      effect: "none",
    },
  },
  {
    id: "electric",
    name: "Electric",
    vibe: "poderoso · hype",
    theme: {
      preset: "electric",
      background: { type: "solid", color: "#0a0a0a" },
      foreground: "#fafafa",
      mutedForeground: "#a3a3a3",
      accent: "#bef264",
      accentForeground: "#0a0a0a",
      font: "poppins",
      titleFont: "poppins",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
  {
    id: "pastel-paper",
    name: "Pastel Paper",
    vibe: "suave · acolhedor",
    theme: {
      preset: "pastel-paper",
      background: { type: "solid", color: "#faf5ef" },
      foreground: "#422c1a",
      mutedForeground: "#78716c",
      accent: "#c084fc",
      accentForeground: "#ffffff",
      font: "dm-sans",
      titleFont: "playfair",
      buttonStyle: "shadow",
      avatarShape: "rounded",
      spacing: "loose",
      effect: "noise",
    },
  },
  {
    id: "ocean",
    name: "Ocean",
    vibe: "fresco · calmo",
    theme: {
      preset: "ocean",
      background: {
        type: "gradient",
        from: "#0ea5e9",
        via: "#06b6d4",
        to: "#14b8a6",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#e0f2fe",
      accent: "#ffffff",
      accentForeground: "#0891b2",
      font: "inter",
      titleFont: "inter",
      buttonStyle: "glass",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "rose",
    name: "Rosé",
    vibe: "chique · feminino",
    theme: {
      preset: "rose",
      background: { type: "solid", color: "#fdf2f8" },
      foreground: "#500724",
      mutedForeground: "#9f1239",
      accent: "#e11d48",
      accentForeground: "#ffffff",
      font: "playfair",
      titleFont: "playfair",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "loose",
      effect: "none",
    },
  },
  {
    id: "noir",
    name: "Noir",
    vibe: "preto · elegante",
    theme: {
      preset: "noir",
      background: { type: "solid", color: "#0a0a0a" },
      foreground: "#fafafa",
      mutedForeground: "#a1a1aa",
      accent: "#27272a",
      accentForeground: "#fafafa",
      font: "inter",
      titleFont: "inter",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "peach-cream",
    name: "Peach Cream",
    vibe: "cremoso · delicado",
    theme: {
      preset: "peach-cream",
      background: {
        type: "gradient",
        from: "#fef3e8",
        via: "#fcc8b5",
        to: "#f97e6a",
        direction: "to-b",
      },
      foreground: "#422006",
      mutedForeground: "#78350f",
      accent: "#ffffff",
      accentForeground: "#422006",
      font: "dm-sans",
      titleFont: "dm-sans",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "bordeaux",
    name: "Bordeaux",
    vibe: "vinho · sofisticado",
    theme: {
      preset: "bordeaux",
      background: { type: "solid", color: "#4a1128" },
      foreground: "#fdf4e7",
      mutedForeground: "#e7c7ae",
      accent: "#fdf4e7",
      accentForeground: "#4a1128",
      font: "playfair",
      titleFont: "playfair",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "pine",
    name: "Pine",
    vibe: "floresta · natural",
    theme: {
      preset: "pine",
      background: { type: "solid", color: "#0f3d2e" },
      foreground: "#f0fdf4",
      mutedForeground: "#bbf7d0",
      accent: "#fef9c3",
      accentForeground: "#0f3d2e",
      font: "dm-sans",
      titleFont: "playfair",
      buttonStyle: "shadow",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "dusk",
    name: "Dusk",
    vibe: "noturno · romântico",
    theme: {
      preset: "dusk",
      background: {
        type: "gradient",
        from: "#1e1b4b",
        via: "#7c3aed",
        to: "#db2777",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#e9d5ff",
      accent: "#ffffff",
      accentForeground: "#1e1b4b",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "glass",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
  {
    id: "grape-pop",
    name: "Grape Pop",
    vibe: "vibrante · divertido",
    theme: {
      preset: "grape-pop",
      background: { type: "solid", color: "#7c3aed" },
      foreground: "#faf5ff",
      mutedForeground: "#e9d5ff",
      accent: "#ddd6fe",
      accentForeground: "#4c1d95",
      font: "poppins",
      titleFont: "poppins",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "mist",
    name: "Mist",
    vibe: "sereno · minimal",
    theme: {
      preset: "mist",
      background: { type: "solid", color: "#cbd5e1" },
      foreground: "#0f172a",
      mutedForeground: "#475569",
      accent: "#f1f5f9",
      accentForeground: "#0f172a",
      font: "inter",
      titleFont: "inter",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "blood-orange",
    name: "Blood Orange",
    vibe: "quente · ousado",
    theme: {
      preset: "blood-orange",
      background: {
        type: "gradient",
        from: "#dc2626",
        via: "#ea580c",
        to: "#f59e0b",
        direction: "to-br",
      },
      foreground: "#ffffff",
      mutedForeground: "#fed7aa",
      accent: "#ffffff",
      accentForeground: "#7c2d12",
      font: "poppins",
      titleFont: "poppins",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
  {
    id: "midnight-glow",
    name: "Midnight Glow",
    vibe: "neon · atmosférico",
    theme: {
      preset: "midnight-glow",
      background: {
        type: "gradient",
        from: "#050505",
        via: "#1a0b2e",
        to: "#4c1d95",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#c4b5fd",
      accent: "#1f1f1f",
      accentForeground: "#ffffff",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
  {
    id: "blush",
    name: "Blush",
    vibe: "suave · amoroso",
    theme: {
      preset: "blush",
      background: { type: "solid", color: "#fce7f3" },
      foreground: "#831843",
      mutedForeground: "#be185d",
      accent: "#ffffff",
      accentForeground: "#831843",
      font: "dm-sans",
      titleFont: "dm-sans",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "loose",
      effect: "none",
    },
  },
  {
    id: "stage",
    name: "Stage",
    vibe: "spotlight · palco",
    theme: {
      preset: "stage",
      background: {
        type: "gradient",
        from: "#0f172a",
        via: "#312e81",
        to: "#6b21a8",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#cbd5e1",
      accent: "#ffffff",
      accentForeground: "#312e81",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "outline",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
  {
    id: "sand",
    name: "Sand",
    vibe: "terra · zen",
    theme: {
      preset: "sand",
      background: { type: "solid", color: "#f5efd9" },
      foreground: "#3f3f1e",
      mutedForeground: "#78716c",
      accent: "#ffffff",
      accentForeground: "#3f3f1e",
      font: "playfair",
      titleFont: "playfair",
      buttonStyle: "outline",
      avatarShape: "circle",
      spacing: "loose",
      effect: "none",
    },
  },
  {
    id: "yellow-black",
    name: "Yellow Brutalist",
    vibe: "ousado · contrastante",
    theme: {
      preset: "yellow-black",
      background: { type: "solid", color: "#0a0a0a" },
      foreground: "#ffe600",
      mutedForeground: "#b8a800",
      accent: "#ffe600",
      accentForeground: "#0a0a0a",
      font: "space-grotesk",
      titleFont: "space-grotesk",
      buttonStyle: "neubrutalism",
      avatarShape: "circle",
      spacing: "normal",
      effect: "grid",
    },
  },
  {
    id: "galaxy",
    name: "Galaxy",
    vibe: "cósmico · misterioso",
    theme: {
      preset: "galaxy",
      background: {
        type: "gradient",
        from: "#0d0221",
        via: "#1a1a4e",
        to: "#0b1d3a",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#a5b4fc",
      accent: "#3b82f6",
      accentForeground: "#ffffff",
      font: "dm-sans",
      titleFont: "instrument-serif",
      buttonStyle: "rounded",
      avatarShape: "circle",
      spacing: "normal",
      effect: "stars",
    },
  },
  {
    id: "glass",
    name: "Glass",
    vibe: "moderno · sofisticado",
    theme: {
      preset: "glass",
      background: {
        type: "gradient",
        from: "#1e3a5f",
        via: "#2563a8",
        to: "#1a365d",
        direction: "to-br",
      },
      foreground: "#0f172a",
      mutedForeground: "#334155",
      accent: "#0f172a",
      accentForeground: "#f8fafc",
      font: "inter",
      titleFont: "inter",
      buttonStyle: "glass",
      avatarShape: "circle",
      spacing: "normal",
      effect: "none",
    },
  },
  {
    id: "photo-dark",
    name: "Photo Dark",
    vibe: "cinematográfico · impactante",
    theme: {
      preset: "photo-dark",
      background: {
        type: "gradient",
        from: "#0f172a",
        via: "#1e3a5f",
        to: "#0f172a",
        direction: "to-b",
      },
      foreground: "#ffffff",
      mutedForeground: "#fb923c",
      accent: "#f97316",
      accentForeground: "#ffffff",
      font: "poppins",
      titleFont: "poppins",
      buttonStyle: "pill",
      avatarShape: "circle",
      spacing: "normal",
      effect: "gradient-mesh",
    },
  },
];

export function getPresetById(id: string | undefined): ThemePreset | undefined {
  if (!id) return undefined;
  return themePresets.find((p) => p.id === id);
}
